PR #34156: [ROCm] Add missing dependencies to header file
Imported from GitHub PR https://github.com/openxla/xla/pull/34156

📝 Summary of Changes
The `rocm_config` bazel target has been included in the `rocm_headers` targets to avoid having to manage the dependency to `rocm_config` target independently when `rocm/rocm_config.h` is included in source code file.
Existing dependencies to `rocm_config` have been removed from BUILD files.

🎯 Justification
The global build of XLA for rocm targets:
`bazel build --config=rocm_clang_official --build_tag_filters -no_oss,-cuda-only,-oneapi-only --test_tag_filters -no_oss,-cuda-only,-oneapi-only //xla/...`
was failing, with the following error:
```
xla/tests/dot_operation_test.cc:43:10: fatal error: 'rocm/rocm_config.h' file not found
  43 | #include "rocm/rocm_config.h"
     |          ^~~~~~~~~~~~~~~~~~~~
140 warnings and 1 error generated.
```
because dot_operation_test.cc includes `rocm.rocm_config.h` but the dependency to `rocm_config` was missing from the build instructions.
Including the `rocm_config` target in the `rocm_headers` target fixed this error.

🚀 Kind of Contribution
Please remove what does not apply: 🐛 Bug Fix

📊 Benchmark (for Performance Improvements)
Not relevant

🧪 Unit Tests:
Not relevant

🧪 Execution Tests:
Not relevant

Copybara import of the project:

--
9ec19ec3802788f0fc50d862e82b59d7fbad0ea4 by Maxime France-Pillois <mfrancep@amd.com>:

[ROCm] Add missing header file dependencies

dot_operation_test.cc includes "rocm.rocm_config.h" but dependency was missing in the build instructions.

--
03c2908ad12e1ab08c3d8be0196240942627efec by Maxime France-Pillois <mfrancep@amd.com>:

Move the dependency to `rocm_config` target to `rocm_headers` and remove independant dependencies to `rocm_config` in build files.

Merging this change closes #34156

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/34156 from ROCm:ci_fix_rocm_header_dot_test 03c2908ad12e1ab08c3d8be0196240942627efec
PiperOrigin-RevId: 836569938