PR #42897: [XLA:GPU][oneAPI] Remove llvm_irgen_test_base dependency from stream executor SYCL tests
Imported from GitHub PR https://github.com/openxla/xla/pull/42897

https://github.com/openxla/xla/commit/e1b7988af67dd0c284a41c2ff42ce74021bdd1fb commit caused the oneAPI GPU build to break with the below error when running stream executor SYCL tests:
```
external/oneapi/compiler/2025.1/include/sycl/ext/oneapi/weak_object.hpp:231:23: error: no member named 'GlobalBufAccessorT' in namespace 'sycl::ext::oneapi::detail'
  231 |   weak_object<detail::GlobalBufAccessorT> MWeakGlobalBuf;
      |               ~~~~~~~~^
```
This PR fixes the error by removing the dependency to `xla::LlvmIrGenTestBase`.
Copybara import of the project:

--
3590286b6db248ccfdb2a822e5f8e3c788fa0304 by Bhavani Subramanian <bhavani1.subramanian@intel.com>:

Remove llvm_irgen_test_base dependency from stream executor SYCL tests

--
54ea0884f4f21dbd8beee525c57305fed25d5dd5 by Bhavani Subramanian <bhavani1.subramanian@intel.com>:

Remove legacy runtime from sycl/BUILD and use HloPjRtGpuTestBase

--
5f7b3f987fc318b53e2f805b237101e3549b2327 by Bhavani Subramanian <bhavani1.subramanian@intel.com>:

Use default PjRt client from HloPjRtGpuTestBase's constructor

Merging this change closes #42897

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/42897 from Intel-tensorflow:bhavanis/remove-llvmirgen-testbase 5f7b3f987fc318b53e2f805b237101e3549b2327
PiperOrigin-RevId: 921313413