PR #61450: Fix link failure in XLA unit tests
Imported from GitHub PR https://github.com/tensorflow/tensorflow/pull/61450

XLA unit tests were unable to link due to undefined reference to stream_executor::Stream::BlockHostUntilDone()
Copybara import of the project:

--
de4a9a85b464f661bb791c18448fe805459ff101 by Andrew Goodbody <andrew.goodbody@linaro.org>:

Fix link failure in XLA unit tests

XLA unit tests were unable to link due to undefined reference to
stream_executor::Stream::BlockHostUntilDone()

Merging this change closes #61450

PiperOrigin-RevId: 553188481