PR #2264: Workaround msvc build by replacing forward decl with decl
Imported from GitHub PR https://github.com/openxla/xla/pull/2264

```
<omitted>\\include\\xstddef(106): error C2678: binary '==': no operator found which takes a left-hand operand of type 'const _Ty' (or there is no acceptable conversion)
        with
        [
            _Ty=xla::TransposePlanCacheKey
        ]
<omitted>\\include\\thread(242): note: could be 'bool std::operator ==(std::thread::id,std::thread::id) noexcept'
<omitted>\\include\\variant(1677): note: or       'bool std::operator ==(std::monostate,std::monostate) noexcept'
<omitted>\\include\\complex(1495): note: or       'bool std::operator ==(const _Ty &,const std::complex<_Other> &)'
...
```

and other 300 lines of incomprehensible long error. Due to the missing of the `opeartor==(...)` for `TransposePlanCacheKey`.
Copybara import of the project:

--
ed7c66a28caf54fadf9dd539ce0a5edf71d9b6ca by Cloud Han <cloudhan@outlook.com>:

Workaround msvc build by replacing forward decl with decl

<omitted>\\include\\xstddef(106): error C2678: binary '==': no operator found which takes a left-hand operand of type 'const _Ty' (or there is no acceptable conversion)
        with
        [
            _Ty=xla::TransposePlanCacheKey
        ]
<omitted>\\include\\thread(242): note: could be 'bool std::operator ==(std::thread::id,std::thread::id) noexcept'
<omitted>\\include\\variant(1677): note: or       'bool std::operator ==(std::monostate,std::monostate) noexcept'
<omitted>\\include\\complex(1495): note: or       'bool std::operator ==(const _Ty &,const std::complex<_Other> &)'
...

and other 300 lines of incomprehensible long error. Due to the missing
of the opeartor==(...) for TransposePlanCacheKey.

--
ec7fab3288395123d1fbd9f00724ef2105d8bffb by Cloud Han <cloudhan@outlook.com>:

Move TransposePlanCacheKey to be a member type of TransposePlanCache

Merging this change closes #2264

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/2264 from cloudhan:msvc ec7fab3288395123d1fbd9f00724ef2105d8bffb
PiperOrigin-RevId: 521752301