PR #14342: Fix //xla/service/gpu:ir_emitter_triton_mem_utils_test in OSS
Imported from GitHub PR https://github.com/openxla/xla/pull/14342

Currently the test fails with:

xla/service/gpu/ir_emitter_triton_mem_utils_test.cc:48:10: fatal error: 'third_party/triton/include/triton/Dialect/Triton/IR/Dialect.h' file not found
   48 | #include "third_party/triton/include/triton/Dialect/Triton/IR/Dialect.h"

Also, using `cc_test` instead of `xla_cc_test` results in linker errors
Copybara import of the project:

--
bdff18bd6948d0249545891a0408f82a4d448fd5 by Sergey Kozub <skozub@nvidia.com>:

Fix //xla/service/gpu:ir_emitter_triton_mem_utils_test in OSS

Merging this change closes #14342

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/14342 from openxla:skozub/ir_emitter_triton_mem_utils_test bdff18bd6948d0249545891a0408f82a4d448fd5
PiperOrigin-RevId: 649342368