PR #14224: Fix build error for LogicalIdThunk::buffer_uses()
Imported from GitHub PR https://github.com/openxla/xla/pull/14224

I tried to build `run_hlo_module` using GCC-13
```bash
bazel build //xla/tools:run_hlo_module
```
and faced build error
```bash
xla/service/cpu/runtime/logical_id_thunk.cc:113:18: error: no declaration matches 'xla::cpu::BufferUses<type> xla::cpu::LogicalIdThunk<type>::buffer_uses() const'
  113 | BufferUses<type> LogicalIdThunk<type>::buffer_uses() const {
      |                  ^~~~~~~~~~~~~~~~~~~~
```

This PR fixes it by using `Thunk::BufferUses` for the output type of `LogicalIdThunk<type>::buffer_uses()` impl.

`BufferUses` alias is declared in `class Thunk`

Related issue: https://github.com/openxla/xla/issues/14172
David, Pawel,  Can you review the fix? @ddunl @pparuzel
Copybara import of the project:

--
ac0401cba4fe7c438a426ddd638c8efa9a40f2f3 by Alexander Pivovarov <pivovaa@amazon.com>:

Fix build error for LogicalIdThunk::buffer_uses()

Merging this change closes #14224

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/14224 from apivovarov:fix_logical_id_thunk ac0401cba4fe7c438a426ddd638c8efa9a40f2f3
PiperOrigin-RevId: 647497158