Use static_cast instead of absl::bit_cast for pointer type cast.
The absl::bit_cast causes a compilation error with older versions of GCC.
Interestingly GCC would complain about a different bit_cast in the same
compilation unit.

```
external/com_google_absl/absl/base/casts.h(169): error: invalid type conversion
          memcpy(static_cast<void*>(std::addressof(dest)),
                 ^
                detected during:
                  instantiation of "Dest absl::lts_20230802::bit_cast<Dest,Source,<unnamed>>(const Source &) [with Dest=uint8_t *__restrict__, Source=void *__restrict__, <unnamed>=0]" at line 64 of external/xla/xla/stream_executor/gpu/ragged_all_to_all_kernel_lib.cu.h
                  instantiation of "void stream_executor::gpu::RaggedAllToAllKernelImpl(const T *, std::array<void *__restrict__, 8UL>, const int64_t *, const int64_t *, const int64_t *, int64_t, int64_t) [with T=uint8_t]" at line 38 of external/xla/xla/stream_executor/cuda/ragged_all_to_all_kernel_cuda.cc
```

Once I remove this bit_cast the error about the other bit_cast goes away and GCC happily compiles the compilation unit. That means this is pretty cursed and likely a GCC bug.

But since using static_cast here has no downsides, let's just do that and
work around the GCC issue.

Fixes https://github.com/openxla/xla/issues/25801

PiperOrigin-RevId: 752646393