[IFRT] Don't use designated initializers, which are a C++20 feature.
Causes a build failure on Windows:
https://github.com/google/jax/actions/runs/5761935221/job/15620752925

external/xla/xla/python/ifrt/device.cc(28): error C7555: use of designated initializers requires at least '/std:c++20'

PiperOrigin-RevId: 553816718