PR #38233: [XLA:GPU][oneAPI] Fix --config=warnings error on SYCL backend
Imported from GitHub PR https://github.com/openxla/xla/pull/38233

PR #37430 enables warnings as errors by default. Due to this change, the following error occurs on the SYCL backend:

`xla/stream_executor/sycl/sycl_context_test.cc:31:46: error: unused variable 'executor' [-Werror,-Wunused-variable] 31 |     TF_ASSERT_OK_AND_ASSIGN(StreamExecutor * executor,`

This PR fixes the above error.

Copybara import of the project:

--
4108f3884ae78efd27c51dd9b8d127a6bfab364e by Bhavani Subramanian <bhavani1.subramanian@intel.com>:

Skip setting up StreamExecutor in sycl_context_test since it is not needed

Merging this change closes #38233

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/38233 from Intel-tensorflow:bhavanis/sycl-fix-warnings 4108f3884ae78efd27c51dd9b8d127a6bfab364e
PiperOrigin-RevId: 875025838