Explicitly tell lambdas to capture existing local variables by copy.
otherwise, MSVC fails to build these files with: error C3493: 'length' cannot be implicitly captured because no default capture mode has been specified

PiperOrigin-RevId: 293456944
Change-Id: Id24cd741f0735d4461e8cd90545b64ca5d9a8b69