PR #35191: [ROCm] Fix jax build with rocm
Imported from GitHub PR https://github.com/openxla/xla/pull/35191

📝 Summary of Changes
While building jax and running its test it complaints about missing hipsolver_potrf_ffi
FFI handler. This change ensures that libs located in data are linked against the targets
where they are set as a dependency.

🎯 Justification
Fixing this issue:
```
jax.errors.JaxRuntimeError: NOT_FOUND: No FFI handler registered for hipsolver_potrf_ffi on a platform ROCM (canonical rocm)
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

🚀 Kind of Contribution
Please remove what does not apply: 🐛 Bug Fix

📊 Benchmark (for Performance Improvements)
Not relevant

🧪 Unit Tests:
CI U-Tests

🧪 Execution Tests:
Not relevant

Copybara import of the project:

--
1cf513b957650bc7e1510cf8bef6bc0285b9d8c9 by Alexandros Theodoridis <atheodor@amd.com>:

Fix jax build with rocm

--
3c7dee35701d8fc1e7fe040389c4ec8fcc1fe475 by Alexandros Theodoridis <atheodor@amd.com>:

Add more libs to data

--
90192b07dd5d0a8ba6acd9f51b3110db70095db4 by Alexandros Theodoridis <atheodor@amd.com>:

Put everhting to data

--
cfa46dd5ce30181b268d0338c901834699988838 by Alexandros Theodoridis <atheodor@amd.com>:

Switch hermetic build to release version of rocm

Merging this change closes #35191

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/35191 from ROCm:fix_jax_build_due_to_missing_lib_handler 4da7de243cfd8d9a1c3aa15bd5de6e0f925c6863
PiperOrigin-RevId: 845610364