Fix JAX build failure under Python 3.12.0rc1.
The distutils module has been removed under Python 3.12, and the code here fails with a ModuleNotFoundError. This occurs because:

```
$ ipython
Python 3.12.0rc1 (main, Aug  7 2023, 13:07:47) [GCC 12.2.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import importlib.util

In [2]: importlib.util.find_spec('distutils.sysconfig')
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 importlib.util.find_spec('distutils.sysconfig')

File <frozen importlib.util>:91, in find_spec(name, package)

ModuleNotFoundError: No module named 'distutils'
```

However, as far as I can tell, we can just unconditionally use sysconfig since Python 3.2, which is well below the minimum Python version requirement of this code.

This change effectively reverts: https://github.com/tensorflow/tensorflow/pull/54292
That change will no longer be tenable once Python 3.12 is released.

PiperOrigin-RevId: 555273752