PR #15780: Fix thunk_executor.cc build failure caused by ABSL_ATTRIBUTE_ALWAYS_INLINE
Imported from GitHub PR https://github.com/openxla/xla/pull/15780

Currently thunk_executor.cc compilation fails if gcc11 is used. Error:
```
xla/service/cpu/runtime/thunk_executor.cc:514:30: error: inlining failed in call to 'always_inline' 'xla::cpu::ThunkExecutor::FifoReadyQueue::FifoReadyQueue(absl::lts_20230802::Span<const long int>)': function body can be overwritten at link time
xla/service/cpu/runtime/thunk_executor.cc:543:51: note: called from here
  543 |   return FifoReadyQueue(absl::Span<const NodeId>());
```

This PR fixes it by replacing `ABSL_ATTRIBUTE_ALWAYS_INLINE` with `inline` in couple places.
Copybara import of the project:

--
08a0433c3afe291da9321a0ea320dfe0d707f25a by Alexander Pivovarov <pivovaa@amazon.com>:

Fix thunk_executor.cc build failure caused by ABSL_ATTRIBUTE_ALWAYS_INLINE

Merging this change closes #15780

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/15780 from apivovarov:fix_always_inline 08a0433c3afe291da9321a0ea320dfe0d707f25a
PiperOrigin-RevId: 660366668