PR #24269: Fix for fusion wrapper on async computations
Imported from GitHub PR https://github.com/openxla/xla/pull/24269

Previously, in JAX if you do a simple stream annotated computation with just a single instruction, i.e.

```python
@compute_on('gpu_stream:1')
@jax.jit
def h(x, y):
  return x * y
```

Then the XLA compiler would fail with an error like

```
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Unsupported instruction opcode: multiply
```

This is because the fusion wrapper would not correctly look inside of async computations, leaving the instructions unfused.

To fix this, we simply add `kCall` and `kAsyncStart` to the set of instructions that are treated recursively in the fusion wrapper.
Copybara import of the project:

--
bef9c2829a585727094c270b6c7e1e05ce304819 by chaserileyroberts <chaser@nvidia.com>:

Added fix for some fusion issues using compute_on

--
1d909f1fb4a5bd11053be35f15e42796f7adb643 by chaserileyroberts <chaser@nvidia.com>:

Update fusion wrapper test

--
0e39915f444607c5518bb7a5ce4a168801bfee8d by chaserileyroberts <chaser@nvidia.com>:

Added {0} to dtype descriptions

--
5e51b3897c45354e929b061d131f8b2a6efde36a by chaser <chaser@nvidia.com>:

xla_cc_test -> xla_test

--
37df8115138ba07ed3f735787f62830d4abafffc by chaser <chaser@nvidia.com>:

RunAndCompare -> RunAndCompareNoHloPasses

Merging this change closes #24269

COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/24269 from chaserileyroberts:chase/compute_on_fusion_fix 37df8115138ba07ed3f735787f62830d4abafffc
PiperOrigin-RevId: 744627904