This is a rollback of https://github.com/tensorflow/tensorflow/commit/fad2024a10840547339c0943782e1706c4a413b7 which broke tensorflow lite ios release. With this commit, the bazel build command failed with the following error. Somehow it is executing the python script as a bash script. We are still investigating why this change broke the build and will probably roll forward this commit once it is fixed on our side.
ERROR: /Volumes/BuildData/tmpfs/src/github/tensorflow/tensorflow/lite/ios/BUILD:103:21: Bundling Preprocessed_TensorFlowLiteC_framework failed: (Exit 2): bundletool failed: error executing command
  (cd /Volumes/BuildData/tmpfs/bazel_output/_bazel_kbuilder/d1b2600cd78e76a92812a06683f5de10/execroot/org_tensorflow && \
  exec env - \
  bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/applebin_ios-ios_x86_64-opt-ST-74bbdaf492e7/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/bundletool_control.json)
# Configuration: 0c9dde86b66380bc8e56c0e3f6860c50847a9e6a9dcfc747f6773735b86e81fd
# Execution platform: @local_execution_config_platform//:platform
from: can't read /var/mail/__future__
from: can't read /var/mail/__future__
from: can't read /var/mail/__future__
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 13: import: command not found
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 19: del: command not found
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 21: import: command not found
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 22: import: command not found
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 23: import: command not found
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 24: import: command not found
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 25: import: command not found
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 26: import: command not found
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 29: syntax error near unexpected token `('
bazel-out/darwin-opt-exec-50AE0418-ST-0d9c66f6a0f7/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool: line 29: `def IsWindows():'
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
PiperOrigin-RevId: 500047127