[XLA:GPU] Refactor cub_sort_kernel.cu.cc to not use abseil
A recent change caused the cuda 11.8 nvcc to barf on any absl::Status use:
```
external/com_google_absl/absl/strings/internal/str_format/bind.h: In constructor 'absl::lts_20230802::str_format_internal::FormatSpecTemplate<Args>::FormatSpecTemplate(const absl::lts_20230802::str_format_internal::ExtendedParsedFormat<absl::lts_20230802::FormatConversionCharSet(C)...>&)':
external/com_google_absl/absl/strings/internal/str_format/bind.h:172:1: error: parse error in template argument list
  172 |     CheckArity<sizeof...(C), sizeof...(Args)>();
      | ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

To be safe and avoid this kind of breakage in this future, this change
factors out the absl usage into cub_sort_thunk.cc, so nvcc doesn't
interact with it at all.