Add missing header include.
In some configurations, this could result in a compile error:
error: 'uint32_t' was not declared in this scope
PiperOrigin-RevId: 581205259