[ROCM] Fix run_hlo_module build on ROCm
`run_hlo_module` depends on `rocm_platform` that implements
BlasLt. Linking would fail with following complaint without
explicitly specifying dependency.

undefined reference to 'stream_executor::rocm::BlasLt::Init()'
undefined reference to 'vtable for stream_executor::rocm::BlasLt'