PR #24269: Fix for fusion wrapper on async computations
Imported from GitHub PR https://github.com/openxla/xla/pull/24269

Previously, in JAX if you do a simple stream annotated computation with just a single instruction, i.e.

```python
@compute_on('gpu_stream:1')
@jax.jit
def h(x, y):
  return x * y
```

Then the XLA compiler would fail with an error like

```
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Unsupported instruction opcode: multiply
```

This is because the fusion wrapper would not correctly look inside of async computations, leaving the instructions unfused.

To fix this, we simply add `kCall` and `kAsyncStart` to the set of instructions that are treated recursively in the fusion wrapper.
Copybara import of the project:

--
ca79462e42622872bfbfc331fec957e1075e0548 by chaserileyroberts <chaser@nvidia.com>:

Added fix for some fusion issues using compute_on

--
207ca0f85ebb849322ae67b94bafbab82a0daa5c by chaserileyroberts <chaser@nvidia.com>:

Update fusion wrapper test

Merging this change closes #24269

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/24269 from chaserileyroberts:chase/compute_on_fusion_fix 207ca0f85ebb849322ae67b94bafbab82a0daa5c
PiperOrigin-RevId: 741475539