PR #23997: Fix the build issue after commit df841fe
Imported from GitHub PR https://github.com/openxla/xla/pull/23997

When running tests, like `bazel test //xla/service/gpu/model:hlo_op_profiler_test`, on a machine with only CUDA configured, the build system will try to build ROCm tests and fail.

Before this change:
```
ERROR: xla/xla/stream_executor/rocm/BUILD:791:13: Compiling xla/stream_executor/rocm/rocm_helpers.cu.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing CppCompile command (from target //xla/stream_executor/rocm:rocm_helpers) external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/xla/stream_executor/rocm/_objs/rocm_helpers/rocm_helpers.cu.pic.d ... (remaining 37 arguments skipped)
/home/svaishay/.cache/bazel/_bazel_svaishay/3b9a2c84bcbdad9b9781b5eb1069603a/execroot/xla/external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc:227: SyntaxWarning: invalid escape sequence '\.'
  re.search('\.cpp$|\.cc$|\.c$|\.cxx$|\.C$', f)]
clang: warning: argument unused during compilation: '--cuda-path=external/cuda_nvcc' [-Wunused-command-line-argument]
xla/stream_executor/rocm/rocm_helpers.cu.cc:16:10: fatal error: 'hip/hip_bfloat16.h' file not found
   16 | #include <hip/hip_bfloat16.h>
      |          ^~~~~~~~~~~~~~~~~~~~
1 error generated.
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.333s, Critical Path: 0.18s
INFO: 28 processes: 28 internal.
ERROR: Build did NOT complete successfully
//xla/service/gpu/model:hlo_op_profiler_test_gpu_a100                 NO STATUS
//xla/service/gpu/model:hlo_op_profiler_test_gpu_any                  NO STATUS
//xla/service/gpu/model:hlo_op_profiler_test_gpu_b200                 NO STATUS
//xla/service/gpu/model:hlo_op_profiler_test_gpu_h100                 NO STATUS
```

After this change:
```
INFO: Build completed successfully, 5 total actions
//xla/service/gpu/model:hlo_op_profiler_test_gpu_a100                    PASSED in 14.9s
//xla/service/gpu/model:hlo_op_profiler_test_gpu_any                     PASSED in 15.4s
//xla/service/gpu/model:hlo_op_profiler_test_gpu_b200                    PASSED in 16.2s
//xla/service/gpu/model:hlo_op_profiler_test_gpu_h100                    PASSED in 14.3s
```
Copybara import of the project:

--
3a3d7ecfd5dca58d70b506f111e26988028e78e0 by Shraiysh Vaishay <svaishay@nvidia.com>:

Fix the build issue after commit df841fe

When running tests, like `bazel test //xla/tests:hlo_op_profiler_test`,
on a machine with only CUDA configured, the build system will try to
build ROCm tests and fail.

This commit fixes the issue by only building ROCm tests if ROCm is
configured and vice versa.

--
6bebc0405cc8bc3a44c44845799b3861ac3376ee by Shraiysh Vaishay <svaishay@nvidia.com>:

address comments

Merging this change closes #23997

FUTURE_COPYBARA_INTEGRATE_REVIEW=https://github.com/openxla/xla/pull/23997 from shraiysh:fix_build_issue 6bebc0405cc8bc3a44c44845799b3861ac3376ee
PiperOrigin-RevId: 745441707