Restore tool/def_file_filter for now
This broke XLA Build with

ERROR: error loading package '': at /tf/xla/workspace2.bzl:17:6: Label '//tools/def_file_filter:def_file_filter_configure.bzl' is invalid because 'tools/def_file_filter' is not a package; perhaps you meant to put the colon here: '//:tools/def_file_filter/def_file_filter_configure.bzl'?
PiperOrigin-RevId: 496744269