Fix the Mac build by rolling back #59536
https://github.com/tensorflow/tensorflow/pull/59536 broke building on Mac. The error is:

    error: no member named 'isnan' in namespace 'std'; did you mean simply 'isnan'?

PiperOrigin-RevId: 510557348