Workaround msvc build by replacing forward decl with decl
<omitted>\\include\\xstddef(106): error C2678: binary '==': no operator found which takes a left-hand operand of type 'const _Ty' (or there is no acceptable conversion)
        with
        [
            _Ty=xla::TransposePlanCacheKey
        ]
<omitted>\\include\\thread(242): note: could be 'bool std::operator ==(std::thread::id,std::thread::id) noexcept'
<omitted>\\include\\variant(1677): note: or       'bool std::operator ==(std::monostate,std::monostate) noexcept'
<omitted>\\include\\complex(1495): note: or       'bool std::operator ==(const _Ty &,const std::complex<_Other> &)'
...

and other 300 lines of incomprehensible long error. Due to the missing
of the opeartor==(...) for TransposePlanCacheKey.